name: flutter_firestore
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: "^0.14.3"
  flutter_form_builder: ^4.2.0
  provider: ^5.0.0
  flutter_search_bar: ^2.1.0
  firebase_auth: "^0.18.3+1"
  flutter_speed_dial: ^1.2.5
  linkable: ^1.0.6
  url_launcher: ^5.4.10
  firebase_storage: "^5.2.0"
  image_picker: ^0.6.7+4
  image_picker_for_web: ^0.1.0+1
  permission_handler: ^5.0.1+1
  flutter_launcher_icons: ^0.8.1
  transparent_image: ^1.0.0
  firebase_core: ^0.5.3
  tutorial_coach_mark: ^0.5.2
  unicorndial: "^1.1.5"
  material_design_icons_flutter: ^4.0.5855
  mdi: ^4.0.0
  carousel_slider: ^3.0.0
  pull_to_reveal: ^0.0.2
  cached_network_image: ^2.5.0
  youtube_player_flutter: ^7.0.0+7
  youtube_player_iframe: ^1.2.0+2
  font_awesome_flutter: ^8.11.0






  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0


dependency_overrides:
  intl: 0.17.0-nullsafety.2
  date_range_picker:
    git:
      url: https://github.com/LempereurBenjamin/date_range_picker

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/ajuntament.png"
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/icon_image.png
    - assets/icon/ajuntament.png
    - assets/escutp.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
